management.endpoints.web.exposure.include: "*"

server:
  servlet:
    context-path: /demoSwagger

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect    
  h2:
    console.enabled: false
    console.path: /h2-console
    console.settings.trace: false 
  mvc: 
    spring.mvc.pathmatch.matching-strategy: ant_path_matcher

spring.profiles.active: prd
